#!/bin/bash

cd ~

export _JAVA_AWT_WM_NONREPARENTING=1
export XCURSOR_SIZE=24
export LIBVA_DRIVER_NAME=nvidia
export XDG_SESSION_TYPE=wayland
export GBM_BACKEND=nvidia-drm
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export SDL_VIDEODRIVER=wayland
export MOZ_ENABLE_WAYLAND=1
export GTK_THEME=Jasper-Dark
export WLR_NO_HARDWARE_CURSORS=1
export QT_QPA_PLATFORM=wayland 
export QT_QPA_PLATFORMTHEME=qt5ct

exec Hyprland &
