vim.api.nvim_exec('language en_US', true)
require('packer-config')
require('lsp-config')
require('settings')
require('mappings')
require('colorschemes-config.gruvbox')
require('telescope-config')
require('treesitter-config')
require('vcs-config')
vim.api.nvim_exec('hi Normal guibg=none ctermbg=none', true)
vim.api.nvim_exec('hi EndOfBuffer guibg=none ctermbg=none', true)
vim.api.nvim_exec('hi StatusLine guibg=none ctermbg=none', true)
vim.api.nvim_exec('hi SpecialKey guibg=none ctermbg=none', true)
vim.api.nvim_exec('hi LineNr guibg=none ctermbg=none', true)
vim.api.nvim_exec('hi Folded guibg=none ctermbg=none', true)
vim.api.nvim_exec('hi NonText guibg=none ctermbg=none', true)
vim.api.nvim_exec('hi VertSplit guibg=none ctermbg=none', true)
vim.api.nvim_exec('hi SignColumn guibg=none ctermbg=none', true)
